
import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import './globals.css'
import Nav from './components/Nav'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className="min-h-screen ">
          <Nav />
          <div className='flex justify-center items-center p-24'>
            {children}
          </div>
        </body>
      </ClerkProvider>
    </html>
  )
}
